# Generated by Django 2.1.7 on 2019-03-11 03:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('SubjectCourse', wagtail.core.blocks.StructBlock([('required_course', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('course_photo', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.URLBlock())]))), ('optional_course', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('course_photo', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.URLBlock())])))], template='subject/blocks/subject_course.html'))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
